"""Golden baseline structural regression tests for document styling."""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from tests.conftest import (
    GOLDEN_DOCX_DIR,
    GOLDEN_FP_DIR,
    RENDER_CASES,
    golden_docx_path,
    golden_fingerprint_path,
    render_case,
)
from tests.docx_structure import (
    compare_reference_subset,
    diff_fingerprints,
    extract_docx_fingerprint,
    fingerprint_from_json,
    fingerprint_to_json,
)

REF_DIR = Path(__file__).resolve().parent / "reference"
MATCH_STATE_PATH = REF_DIR / "MATCH_STATE.md"

REF_CASES = [
    ("moa", "MOA Glycine IP.docx", "moa"),
    ("spec", "Spec Glycine IP.docx", "spec"),
    ("protocol", "GLYCINE IP.docx", "protocol"),
    ("coa", "Glycine IP 010326.docx", "coa"),
    ("aws", "GLYCINE IP.docx", "aws"),
]

# Collected during test_client_reference_subset_if_present; flushed after session.
_reference_match_results: dict[str, tuple[bool, str]] = {}


@pytest.fixture(scope="session", autouse=True)
def flush_reference_match_state():
    """Write tests/reference/MATCH_STATE.md after client-reference comparisons run."""
    yield
    if not _reference_match_results:
        return
    lines = [
        "# Client reference subset match state",
        "",
        "Auto-generated by `tests/test_style_regression.py`.",
        "Compares renderer output (glycine fixtures) vs client reference DOCX:",
        "margins, page borders, and `header2.xml` table grids.",
        "",
        "| Document | Match | Details |",
        "|----------|-------|---------|",
    ]
    for ref_key, ref_filename, _ in REF_CASES:
        if ref_key not in _reference_match_results:
            lines.append(f"| {ref_key} | skipped | reference file not present |")
            continue
        ok, message = _reference_match_results[ref_key]
        status = "PASS" if ok else "DIVERGE"
        detail = message.replace("\n", "; ")
        lines.append(f"| {ref_key} | {status} | {detail} |")
    lines.append("")
    MATCH_STATE_PATH.write_text("\n".join(lines), encoding="utf-8")
    _reference_match_results.clear()


def _write_golden(key: str, rendered: Path) -> None:
    GOLDEN_DOCX_DIR.mkdir(parents=True, exist_ok=True)
    GOLDEN_FP_DIR.mkdir(parents=True, exist_ok=True)
    dest_docx = golden_docx_path(key)
    shutil.copy2(rendered, dest_docx)
    fp = extract_docx_fingerprint(dest_docx)
    golden_fingerprint_path(key).write_text(fingerprint_to_json(fp), encoding="utf-8")


def test_structural_fingerprint_matches_golden(
    document_renderer,
    common_kwargs,
    render_case_param,
    update_golden,
):
    """Render each doc type and assert structural fingerprint matches golden baseline."""
    case = render_case_param
    key = case["key"]
    rendered = render_case(document_renderer, case, common_kwargs)

    if update_golden:
        _write_golden(key, rendered)
        pytest.skip(f"Updated golden baseline for {key}")

    golden_fp_path = golden_fingerprint_path(key)
    golden_docx = golden_docx_path(key)
    assert golden_fp_path.exists(), f"Missing golden fingerprint: {golden_fp_path}"
    assert golden_docx.exists(), f"Missing golden DOCX: {golden_docx}"

    expected = fingerprint_from_json(golden_fp_path.read_text(encoding="utf-8"))
    actual = extract_docx_fingerprint(rendered)

    if actual != expected:
        pytest.fail(diff_fingerprints(expected, actual))


def test_determinism_double_extract(document_renderer, common_kwargs, render_case_param):
    """Same rendered file yields identical fingerprint on repeated extraction."""
    rendered = render_case(document_renderer, render_case_param, common_kwargs)
    first = extract_docx_fingerprint(rendered)
    second = extract_docx_fingerprint(rendered)
    assert first == second


def test_fingerprint_diff_format():
    """Diff helper reports readable expected vs actual (harness-only perturbation)."""
    expected = {
        "sections": [{"margins": {"top": "720", "footer": "288"}}],
        "page_fields": [" PAGE "],
    }
    actual = {
        "sections": [{"margins": {"top": "1440", "footer": "288"}}],
        "page_fields": [" PAGE  \\* Arabic  \\* MERGEFORMAT "],
    }
    diff = diff_fingerprints(expected, actual)
    assert "sections[0].margins.top" in diff
    assert "expected:" in diff
    assert "actual:" in diff
    assert "1440" in diff
    assert "page_fields" in diff


@pytest.mark.parametrize("ref_key,ref_filename,render_key", REF_CASES)
def test_client_reference_subset_if_present(
    document_renderer,
    common_kwargs,
    ref_key,
    ref_filename,
    render_key,
):
    """Compare margins/borders/header2 grids against client reference DOCX when available."""
    ref_path = REF_DIR / ref_filename
    if not ref_path.exists():
        pytest.skip(
            "Client reference DOCX not in repo — place files in tests/reference/ to enable"
        )

    case = next(c for c in RENDER_CASES if c["key"] == render_key)
    rendered = render_case(document_renderer, case, common_kwargs)

    ref_fp = extract_docx_fingerprint(ref_path)
    gen_fp = extract_docx_fingerprint(rendered)
    ok, message = compare_reference_subset(ref_fp, gen_fp)
    _reference_match_results[ref_key] = (ok, message)
    # Record match state for §1.2 margin audit; do not fail golden gate on known divergences.
    assert message, "Reference comparison must produce a result message"
